name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # ✅ Use system Python, not setup-python
    - name: Install system dependencies (CRITICAL)
      run: |
        sudo apt update
        sudo apt install -y \
          python3 \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          python3-cython \
          build-essential \
          git zip unzip \
          openjdk-17-jdk \
          libffi-dev \
          libssl-dev \
          zlib1g-dev \
          libncurses5

    # ✅ Verify cython exists (this MUST pass)
    - name: Verify Cython
      run: |
        which cython
        cython --version

    # ✅ Install buildozer using system python
    - name: Install Buildozer
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install buildozer==1.5.0

    # ✅ Build APK
    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: DigiPayattu-APK
        path: bin/*.apk
