name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 🔴 Install Cython as SYSTEM COMMAND
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          python3-dev \
          python3-setuptools \
          cython3 \
          build-essential \
          git zip unzip \
          openjdk-17-jdk \
          libffi-dev \
          libssl-dev \
          zlib1g-dev \
          libncurses5

    # 🔴 Create cython command explicitly
    - name: Ensure cython command exists
      run: |
        which cython || true
        which cython3
        sudo ln -sf /usr/bin/cython3 /usr/bin/cython
        cython --version

    # 🔴 Install buildozer AFTER cython exists
    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        python -m pip install buildozer

    # 🔴 Build APK
    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: DigiPayattu-APK
        path: bin/*.apk
