name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 🔴 Install cython at OS + Python level
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          python3-dev \
          cython3 \
          build-essential \
          git zip unzip \
          openjdk-17-jdk \
          libffi-dev \
          libssl-dev \
          zlib1g-dev \
          libncurses5

    # 🔴 Force correct cython in pip (Buildozer compatible)
    - name: Install Python tools
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install "cython<3" virtualenv

    # 🔴 Install buildozer AFTER cython
    - name: Install Buildozer
      run: |
        python -m pip install buildozer

    # 🔴 HARD PATH FIX
    - name: Fix PATH for cython
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        which cython || true
        cython --version || true

    # 🔴 Build using python module (IMPORTANT)
    - name: Build APK
      run: |
        python -m buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: DigiPayattu-APK
        path: bin/*.apk
